#!/usr/bin/env python3
# is a rsa factoring challenge

import sys
import subprocess

def factorize(num):
    result = subprocess.check_output(['factor', str(num)], text=True)
    factors = list(map(int, result.split()[1:]))
    return factors

def check_factorization(num, factors):
    p, q = min(factors), max(factors)
    print(f"{num}={p}*{q}")

if len(sys.argv) != 2:
    print('Usage: rsa <file>')
    sys.exit(1)
else:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            num = int(line.strip())
            factors = factorize(num)
            check_factorization(num, factors)
